[package]
name = "rapid_sync"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "= 4.4.6", features = ["derive"] }
walkdir = "= 2.4.0"
sha2 = "= 0.10.8"